name:                travis-example
version:             0.1.0.0
github:              "Hogeyama/travis-example"
license:             BSD3
author:              "Naoki Iwayama"
maintainer:          "gan13027830@gmail.com"
copyright:           "(c) Naoki Iwayama 2017"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Hogeyama/travis-example#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  travis-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - travis-example

tests:
  travis-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - travis-example
